name: Mirror @runilib/formura

on:
  push:
    branches:
      - main
    paths:
      - "packages/formura/**"
      - ".github/workflows/react-walkit/mirror-package.yml"
      - ".github/workflows/react-walkit/mirror-formura.yml"
  workflow_dispatch:

jobs:
  mirror-formura:
    uses: ./.github/workflows/react-walkit/mirror-package.yml
    with:
      package_path: packages/formura
      target_repo: runilib/formura
      target_branch: main
    secrets:
      mirror_push_token: ${{ secrets.MIRROR_PUSH_TOKEN }}