import { Platform, StyleSheet } from 'react-native';

export const formExampleStyles = StyleSheet.create({
  sectionCard: {
    marginTop: 24,
    marginBottom: 8,
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 4,
  },

  customerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  customerEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#b7791f',
    marginBottom: 6,
  },
  customerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a1108',
    letterSpacing: -0.7,
  },
  customerSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    color: '#7a6e5e',
    maxWidth: 240,
  },
  customerPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#fff4df',
    borderWidth: 1,
    borderColor: '#f5dfb2',
  },
  customerPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#b7791f',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  customerPreview: {
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#eff6ff',
    marginBottom: 18,
  },
  customerPreviewLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#2563eb',
    marginBottom: 10,
  },
  customerPreviewNumber: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: '#10203a',
    marginBottom: 12,
  },
  customerPreviewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  customerPreviewMetaText: {
    fontSize: 12,
    color: '#4f6382',
    fontWeight: '600',
  },
  customerPreviewDepartment: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    color: '#2563eb',
    fontSize: 11,
    fontWeight: '700',
  },
  successBox: {
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#edfdf2',
    borderWidth: 1,
    borderColor: '#c8f1d3',
  },
  successText: {
    color: '#1f7a43',
    fontSize: 13,
    fontWeight: '700',
  },
  sectionBlock: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#faf7f1',
    borderWidth: 1,
    borderColor: '#efe7da',
  },
  sectionBlockTitle: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
    marginBottom: 12,
  },
  tips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  tip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ece1cf',
    color: '#7a6e5e',
    fontSize: 11,
    fontWeight: '600',
  },
  errorBox: {
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#fff0ec',
    borderWidth: 1,
    borderColor: '#ffd1c4',
  },
  errorText: {
    color: '#b8401d',
    fontSize: 13,
    fontWeight: '700',
  },
  submitButton: {
    marginTop: 6,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#2563eb',
    shadowColor: '#2563eb',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 4,
  },

  resolverShowcaseCard: {
    marginTop: 24,
    marginBottom: 8,
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 5,
  },
  resolverHeader: {
    gap: 14,
    marginBottom: 18,
  },
  resolverEyebrow: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.18)',
  },
  resolverEyebrowText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#fbbf24',
  },
  resolverTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#10203a',
    letterSpacing: -0.7,
  },
  resolverSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    color: '#5f6f88',
  },
  resolverSwitchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resolverSwitch: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.12)',
    backgroundColor: '#f8fbff',
    minWidth: 132,
  },
  resolverSwitchActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.16)',
    borderColor: 'rgba(96, 165, 250, 0.36)',
  },
  resolverSwitchLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#20304b',
  },
  resolverSwitchNote: {
    marginTop: 3,
    fontSize: 11,
    color: '#7a869a',
  },

  resolverCard: {
    gap: 16,
  },
  resolverBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  resolverBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  resolverHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#10203a',
    letterSpacing: -0.5,
  },
  resolverText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#5f6f88',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(37, 99, 235, 0.05)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.1)',
  },
  chipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#31507f',
  },
  previewCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#f7fbff',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.1)',
    gap: 10,
  },
  previewHeading: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#2563eb',
  },
  previewValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#10203a',
    letterSpacing: -0.5,
  },
  previewText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#5f6f88',
  },
  payloadCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#f7fbff',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.1)',
  },
  payloadCode: {
    fontSize: 12,
    lineHeight: 18,
    color: '#52627d',
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: 'Courier',
    }),
  },
  footerText: {
    fontSize: 12.5,
    lineHeight: 19,
    color: '#5f6f88',
  },
  actionRow: {
    marginTop: 4,
    gap: 12,
  },
  secondaryButton: {
    minHeight: 52,
    paddingHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.14)',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#20304b',
  },

  formRow: {
    flexDirection: 'row',
    gap: 12,
  },
  halfField: {
    flex: 1,
  },

  fieldRoot: {
    marginBottom: 0,
    gap: 8,
  },
  fieldLabel: {
    fontSize: 11.5,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
  },
  fieldInput: {
    minHeight: 52,
    borderWidth: 1.5,
    borderColor: '#e7dccb',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1a1108',
    backgroundColor: '#fffdf9',
  },
  fieldError: {
    fontSize: 12,
    color: '#c2410c',
    fontWeight: '600',
  },
  fieldHint: {
    fontSize: 12,
    color: '#8a7c69',
  },
  checkboxRow: {
    alignItems: 'center',
    gap: 12,
  },
  checkboxBox: {
    borderRadius: 7,
    borderColor: '#d9cfbe',
  },
  checkboxLabel: {
    color: '#3f3427',
    fontWeight: '600',
  },
  optionRow: {
    borderRadius: 12,
    marginBottom: 8,
  },
  optionLabel: {
    fontSize: 14,
    color: '#1a1108',
  },
  optionModalBackdrop: {
    backgroundColor: 'rgba(8, 15, 30, 0.56)',
  },
  optionModalCard: {
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  customMaskField: {
    gap: 10,
  },
  customMaskHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  customMaskLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  customMaskLabel: {
    fontSize: 11.5,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
  },
  customMaskRequired: {
    fontSize: 12,
    fontWeight: '800',
    color: '#d9485f',
  },
  customMaskStatus: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  customMaskStatusIdle: {
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    borderColor: 'rgba(148, 163, 184, 0.18)',
  },
  customMaskStatusReady: {
    backgroundColor: 'rgba(52, 211, 153, 0.12)',
    borderColor: 'rgba(52, 211, 153, 0.24)',
  },
  customMaskStatusError: {
    backgroundColor: 'rgba(251, 113, 133, 0.12)',
    borderColor: 'rgba(251, 113, 133, 0.24)',
  },
  customMaskStatusText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#334155',
  },
  customMaskShell: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#eadfce',
    backgroundColor: '#fffdf9',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  customMaskShellReady: {
    borderColor: '#6ee7b7',
    backgroundColor: '#fcfffd',
  },
  customMaskShellError: {
    borderColor: '#fda4af',
    backgroundColor: '#fff5f6',
  },
  customMaskPrefixBadge: {
    minWidth: 50,
    height: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: '#fff0eb',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customMaskPrefixText: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.9,
    color: '#c2410c',
  },
  customMaskInput: {
    flex: 1,
    minHeight: 44,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 1.4,
    color: '#1a1108',
    paddingVertical: 0,
  },
  customMaskFooter: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  customMaskHint: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: '#8a7c69',
  },
  customMaskError: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: '#c2410c',
    fontWeight: '600',
  },
  customMaskMeta: {
    fontSize: 11,
    fontWeight: '700',
    color: '#8a7c69',
  },
  controllerSelectField: {
    gap: 10,
  },
  controllerSelectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  controllerSelectLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  controllerSelectLabel: {
    fontSize: 11.5,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
  },
  controllerSelectRequired: {
    fontSize: 12,
    fontWeight: '800',
    color: '#2563eb',
  },
  controllerSelectBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(37, 99, 235, 0.16)',
  },
  controllerSelectBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#2563eb',
  },
  controllerSelectTrigger: {
    minHeight: 58,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: '#dbe7ff',
    backgroundColor: '#f8fbff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  controllerSelectTriggerError: {
    borderColor: '#fda4af',
    backgroundColor: '#fff5f6',
  },
  controllerSelectTriggerBody: {
    flex: 1,
    gap: 2,
  },
  controllerSelectCaption: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#64748b',
  },
  controllerSelectValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0f172a',
  },
  controllerSelectPlaceholder: {
    color: '#94a3b8',
  },
  controllerSelectChevron: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2563eb',
  },
  controllerSelectFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  controllerSelectShortcut: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
  },
  controllerSelectShortcutText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#2563eb',
  },
  controllerSelectOption: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#dbe3f0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  controllerSelectOptionActive: {
    borderColor: '#93c5fd',
    backgroundColor: '#eff6ff',
  },
  controllerSelectOptionNote: {
    fontSize: 12,
    color: '#64748b',
  },
  controllerSelectCheck: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2563eb',
  },
});
