import { Platform, StyleSheet } from 'react-native';

export const formExampleStyles = StyleSheet.create({
  sectionCard: {
    marginTop: 24,
    marginBottom: 8,
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 20,
    elevation: 4,
  },

  customerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  customerEyebrow: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#b7791f',
    marginBottom: 6,
  },
  customerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a1108',
    letterSpacing: -0.7,
  },
  customerSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    color: '#7a6e5e',
    maxWidth: 240,
  },
  customerPill: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#fff4df',
    borderWidth: 1,
    borderColor: '#f5dfb2',
  },
  customerPillText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#b7791f',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  customerPreview: {
    padding: 18,
    borderRadius: 22,
    backgroundColor: '#13213a',
    marginBottom: 18,
  },
  customerPreviewLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#93c5fd',
    marginBottom: 10,
  },
  customerPreviewNumber: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 1.2,
    color: '#eff6ff',
    marginBottom: 12,
  },
  customerPreviewMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  customerPreviewMetaText: {
    fontSize: 12,
    color: '#dbeafe',
    fontWeight: '600',
  },
  customerPreviewDepartment: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.12)',
    color: '#dbeafe',
    fontSize: 11,
    fontWeight: '700',
  },
  successBox: {
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#edfdf2',
    borderWidth: 1,
    borderColor: '#c8f1d3',
  },
  successText: {
    color: '#1f7a43',
    fontSize: 13,
    fontWeight: '700',
  },
  sectionBlock: {
    marginBottom: 18,
    padding: 16,
    borderRadius: 20,
    backgroundColor: '#faf7f1',
    borderWidth: 1,
    borderColor: '#efe7da',
  },
  sectionBlockTitle: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
    marginBottom: 12,
  },
  tips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  tip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#ece1cf',
    color: '#7a6e5e',
    fontSize: 11,
    fontWeight: '600',
  },
  errorBox: {
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#fff0ec',
    borderWidth: 1,
    borderColor: '#ffd1c4',
  },
  errorText: {
    color: '#b8401d',
    fontSize: 13,
    fontWeight: '700',
  },
  submitButton: {
    marginTop: 6,
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: '#1d4ed8',
    shadowColor: '#1d4ed8',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 4,
  },

  resolverShowcaseCard: {
    marginTop: 24,
    marginBottom: 8,
    padding: 20,
    borderRadius: 24,
    backgroundColor: '#121b2d',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 5,
  },
  resolverHeader: {
    gap: 14,
    marginBottom: 18,
  },
  resolverEyebrow: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(245, 158, 11, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 158, 11, 0.18)',
  },
  resolverEyebrowText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#fbbf24',
  },
  resolverTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#f8fafc',
    letterSpacing: -0.7,
  },
  resolverSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    color: '#94a3b8',
  },
  resolverSwitchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  resolverSwitch: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
    backgroundColor: 'rgba(255,255,255,0.03)',
    minWidth: 132,
  },
  resolverSwitchActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.16)',
    borderColor: 'rgba(96, 165, 250, 0.36)',
  },
  resolverSwitchLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#e2e8f0',
  },
  resolverSwitchNote: {
    marginTop: 3,
    fontSize: 11,
    color: '#94a3b8',
  },

  resolverCard: {
    gap: 16,
  },
  resolverBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  resolverBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  resolverHeading: {
    fontSize: 20,
    fontWeight: '800',
    color: '#f8fafc',
    letterSpacing: -0.5,
  },
  resolverText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#cbd5e1',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.18)',
  },
  chipText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#dbeafe',
  },
  previewCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.48)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
    gap: 10,
  },
  previewHeading: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#93c5fd',
  },
  previewValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#f8fafc',
    letterSpacing: -0.5,
  },
  previewText: {
    fontSize: 13,
    lineHeight: 20,
    color: '#cbd5e1',
  },
  payloadCard: {
    padding: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(2, 6, 23, 0.62)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.14)',
  },
  payloadCode: {
    fontSize: 12,
    lineHeight: 18,
    color: '#cbd5e1',
    fontFamily: Platform.select({
      ios: 'Menlo',
      android: 'monospace',
      default: 'Courier',
    }),
  },
  footerText: {
    fontSize: 12.5,
    lineHeight: 19,
    color: '#94a3b8',
  },

  formRow: {
    flexDirection: 'row',
    gap: 12,
  },
  halfField: {
    flex: 1,
  },

  fieldRoot: {
    marginBottom: 0,
    gap: 8,
  },
  fieldLabel: {
    fontSize: 11.5,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: '#6f6251',
  },
  fieldInput: {
    minHeight: 52,
    borderWidth: 1.5,
    borderColor: '#e7dccb',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#1a1108',
    backgroundColor: '#fffdf9',
  },
  fieldError: {
    fontSize: 12,
    color: '#c2410c',
    fontWeight: '600',
  },
  fieldHint: {
    fontSize: 12,
    color: '#8a7c69',
  },
  checkboxRow: {
    alignItems: 'center',
    gap: 12,
  },
  checkboxBox: {
    borderRadius: 7,
    borderColor: '#d9cfbe',
  },
  checkboxLabel: {
    color: '#3f3427',
    fontWeight: '600',
  },
  optionRow: {
    borderRadius: 12,
    marginBottom: 8,
  },
  optionLabel: {
    fontSize: 14,
    color: '#1a1108',
  },
  optionModalBackdrop: {
    backgroundColor: 'rgba(8, 15, 30, 0.56)',
  },
  optionModalCard: {
    borderRadius: 20,
    backgroundColor: '#fff',
  },
});
