// ─── Barrel re-export ───────────────────────────────────────────────────────────
// All types are organized into domain-specific files and re-exported here
// so that existing `from '../types/types'` imports continue to work.
// ─────────────────────────────────────────────────────────────────────────────────

export type { FileSourceType, FileValue } from '../core/field-builders/file/types';
export type {
  PasswordRule,
  StrengthConfig,
  StrengthResult,
  StrengthRuleConfig,
  StrengthScoreLevel,
} from '../core/field-builders/password/types';
export type { PhoneValue } from '../core/field-builders/phone/countries';
export type { PhoneCountryLayout } from '../core/field-builders/phone/types';
export type {
  AsyncValidator,
  EmptyProps,
  FieldBehaviorConfig,
  FieldDescriptor,
  FieldRenderHandlers,
  FieldRenderProps,
  FieldRenderState,
  FieldState,
  FieldStyleValue,
  FieldType,
  FieldUiRenderers,
  ISelectOption,
  NativeStyleValue,
  Platform,
  PlatformStyleValue,
  SelectOption,
  SelectPickerRenderContext,
  SyncValidator,
  Validator,
} from './field';
export type {
  BaseFormProps,
  FieldController,
  FieldErrorComponent,
  FieldErrorProps,
  FieldLabelProps,
  FocusableFieldHandle,
  FormComponent,
  FormProps,
  SubmitButtonComponent,
  SubmitButtonProps,
  UseFormBridgeReturn,
} from './form';
export type {
  OptionsFetcher,
  OptionsFetcherContext,
  ResolverResult,
  SchemaResolver,
  UseFormOptions,
  ValidationTrigger,
} from './options';
export type {
  FormSchema,
  FormSchemaEntry,
  FormState,
  FormStatus,
  ResolvedFieldDescriptor,
  SchemaFieldType,
  SchemaValues,
} from './schema';
export type {
  ExtraFieldProps,
  FieldComponent,
  FieldComponents,
  FieldPropsForSchemaEntry,
  FieldStyleProps,
  FieldTheme,
  FieldUiOverrides,
  FormBridgeUiOptions,
  FormUiOverrides,
  PlatformFieldUiForType,
  PlatformFieldUiOverrides,
  PlatformFormUiOverrides,
  PlatformGlobalFieldUiOverrides,
  PlatformSubmitUiOverrides,
  SubmitUiOverrides,
} from './ui';
export type {
  NativeAsyncAutocompleteFieldUiOverrides,
  NativeCheckboxFieldUiOverrides,
  NativeFieldSlot,
  NativeFieldUiOverrides,
  NativeFileFieldItemRenderContext,
  NativeFileFieldRenderContext,
  NativeFileFieldUiOverrides,
  NativeFormUiOverrides,
  NativeGlobalFieldUiOverrides,
  NativeOtpFieldUiOverrides,
  NativePasswordFieldRenderContext,
  NativePasswordFieldRuleRenderContext,
  NativePasswordFieldUiOverrides,
  NativePhoneFieldCountryItemRenderContext,
  NativePhoneFieldRenderContext,
  NativePhoneFieldUiOverrides,
  NativeSelectFieldUiOverrides,
  NativeSubmitUiOverrides,
  NativeSwitchFieldUiOverrides,
  NativeTextFieldUiOverrides,
} from './ui-native';
export type {
  WebAsyncAutocompleteFieldUiOverrides,
  WebCheckboxFieldUiOverrides,
  WebFieldSlot,
  WebFieldUiOverrides,
  WebFileFieldItemRenderContext,
  WebFileFieldRenderContext,
  WebFileFieldUiOverrides,
  WebFormUiOverrides,
  WebGlobalFieldUiOverrides,
  WebOtpFieldUiOverrides,
  WebPasswordFieldRenderContext,
  WebPasswordFieldRuleRenderContext,
  WebPasswordFieldUiOverrides,
  WebPhoneFieldCountryItemRenderContext,
  WebPhoneFieldRenderContext,
  WebPhoneFieldUiOverrides,
  WebRadioFieldUiOverrides,
  WebSelectFieldUiOverrides,
  WebSubmitUiOverrides,
  WebSwitchFieldUiOverrides,
  WebTextareaFieldUiOverrides,
  WebTextFieldUiOverrides,
} from './ui-web';
