// ─── Barrel re-export ───────────────────────────────────────────────────────────
// All types are organized into domain-specific files and re-exported here
// so that existing `from '../types/types'` imports continue to work.
// ─────────────────────────────────────────────────────────────────────────────────

export type { FileSourceType, FileValue } from '../core/field-builders/file/types';
export type {
  PasswordRule,
  StrengthConfig,
  StrengthResult,
  StrengthRuleConfig,
  StrengthScoreLevel,
} from '../core/field-builders/password/types';
export type { PhoneValue } from '../core/field-builders/phone/countries';
export type { PhoneCountryLayout } from '../core/field-builders/phone/types';
export type {
  AsyncValidator,
  EmptyProps,
  FieldDescriptor,
  FieldRenderersProps,
  FieldRenderHandlers,
  FieldRenderProps,
  FieldRenderState,
  FieldState,
  FieldStyleValue,
  FieldType,
  ISelectOption,
  NativeStyleValue,
  Platform,
  PlatformStyleValue,
  SelectOption,
  SelectPickerRenderContext,
  SyncValidator,
  Validator,
} from './field';
export type {
  BaseFormProps,
  FieldController,
  FieldErrorComponent,
  FieldErrorProps,
  FieldLabelProps,
  FocusableFieldHandle,
  FormComponent,
  FormProps,
  SubmitButtonComponent,
  SubmitButtonProps,
  UseFormBridgeReturn,
} from './form';
export type {
  globalDefaultsContext,
  OptionsFetcher,
  OptionsFetcherContext,
  ResolverResult,
  SchemaValidatorResolver,
  UseFormBridgeOptions,
  ValidationTrigger,
} from './options';
export type {
  FormSchema,
  FormSchemaEntry,
  FormState,
  FormStatus,
  ResolvedFieldDescriptor,
  SchemaFieldType,
  SchemaShape,
  SchemaValues,
} from './schema';
export type {
  ExtraFieldProps,
  FieldComponent,
  FieldComponents,
  FieldPropsForSchemaEntry,
  FieldPropsOverrides,
  FieldStyleProps,
  FieldTheme,
  FormBridgeOptions,
  FormPropsOverrides,
  PlatformFieldPropsForType,
  PlatformFieldPropsOverrides,
  PlatformFormPropsOverrides,
  PlatformGlobalFieldPropsOverrides,
  PlatformSubmitPropsOverrides,
  SubmitPropsOverrides,
} from './ui';
export type {
  NativeAsyncAutocompleteFieldPropsOverrides,
  NativeCheckboxFieldPropsOverrides,
  NativeFieldPropsOverrides,
  NativeFieldSlot,
  NativeFileFieldItemRenderContext,
  NativeFileFieldPropsOverrides,
  NativeFileFieldRenderContext,
  NativeFormPropsOverrides,
  NativeGlobalFieldPropsOverrides,
  NativeOtpFieldPropsOverrides,
  NativePasswordFieldPropsOverrides,
  NativePasswordFieldRenderContext,
  NativePasswordFieldRuleRenderContext,
  NativePhoneFieldCountryItemRenderContext,
  NativePhoneFieldPropsOverrides,
  NativePhoneFieldRenderContext,
  NativeSelectFieldPropsOverrides,
  NativeSubmitPropsOverrides,
  NativeSwitchFieldPropsOverrides,
  NativeTextFieldPropsOverrides,
} from './ui-native';
export type {
  WebAsyncAutocompleteFieldPropsOverrides,
  WebCheckboxFieldPropsOverrides,
  WebFieldPropsOverrides,
  WebFieldSlot,
  WebFileFieldItemRenderContext,
  WebFileFieldPropsOverrides,
  WebFileFieldRenderContext,
  WebFormPropsOverrides,
  WebGlobalFieldPropsOverrides,
  WebOtpFieldPropsOverrides,
  WebPasswordFieldPropsOverrides,
  WebPasswordFieldRenderContext,
  WebPasswordFieldRuleRenderContext,
  WebPhoneFieldCountryItemRenderContext,
  WebPhoneFieldPropsOverrides,
  WebPhoneFieldRenderContext,
  WebRadioFieldPropsOverrides,
  WebSelectFieldPropsOverrides,
  WebSubmitPropsOverrides,
  WebSwitchFieldPropsOverrides,
  WebTextareaFieldPropsOverrides,
  WebTextFieldPropsOverrides,
} from './ui-web';
export type {
  FieldReference,
  ValidationContext,
  ValidationErrorMap,
  ValidationIssue,
  ValidationIssueInput,
  ValidationPath,
  ValidationPathSegment,
  ValidationResult,
  ValidatorResult,
} from './validation';
